import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { GoogleOAuthProvider } from "@react-oauth/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Caretakr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId={process.env.OAUTH_CLIENT_ID || ""}>
        <body className={inter.className}>
          {children}
          <Toaster />
        </body>
      </GoogleOAuthProvider>
    </html>
  );
}
